/**
 * Catalog Seed — Yoga Bible
 * One-time populate of course_catalog from cleaned CSV data.
 * Admin-only. POST /.netlify/functions/catalog-seed?confirm=seed
 * Idempotent: skips if collection already has documents.
 */

const { getDb } = require('./shared/firestore');
const { requireAuth } = require('./shared/auth');
const { jsonResponse, optionsResponse } = require('./shared/utils');

// =========================================================================
// Cleaned seed data — from Applications - Course Catalog.csv
// Fixes applied: typos corrected, raw date labels replaced, corrupted row
// and empty separators removed.
// =========================================================================
const SEED_DATA = [
  // === YTT 200h — 18 Weeks Flexible ===
  { course_id: 'YTT200-18W', course_name: '200-hour 18 Weeks Flexible Yoga Teacher Training', category: 'Education', track: '18 Weeks Flexible', cohort_id: '2026-03-06', cohort_label: 'March\u2013June 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=46&prodId=100078', price_full: 23750, currency: 'DKK', deposit_amount: '', allow_deposit: true, allow_instalments: true, max_instalments: 12, notes: '', sort_key: '', open_status: '' },
  { course_id: 'YTT200-18W', course_name: '200-hour 18 Weeks Flexible Yoga Teacher Training', category: 'Education', track: '18 Weeks Flexible', cohort_id: '2026-08-12', cohort_label: 'August\u2013December 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=46&prodId=100210', price_full: 23750, currency: 'DKK', deposit_amount: '3750', allow_deposit: true, allow_instalments: true, max_instalments: 12, notes: '', sort_key: '', open_status: 'Open' },

  // === YTT 200h — 4 Weeks Intensive ===
  { course_id: 'YTT200-4W', course_name: '200-hour 4 Weeks Intensive Yoga Teacher Training', category: 'Education', track: '4 Weeks Intensive', cohort_id: '2026-02', cohort_label: 'February 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=46&prodId=100113', price_full: 23750, currency: 'DKK', deposit_amount: '', allow_deposit: true, allow_instalments: true, max_instalments: 12, notes: '', sort_key: '', open_status: '' },
  { course_id: 'YTT200-4W', course_name: '200-hour 4 Weeks Intensive Yoga Teacher Training', category: 'Education', track: '4 Weeks Intensive', cohort_id: '2026-03', cohort_label: 'March 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=46&prodId=100120', price_full: 23750, currency: 'DKK', deposit_amount: '', allow_deposit: true, allow_instalments: true, max_instalments: 12, notes: '', sort_key: '', open_status: '' },
  { course_id: 'YTT200-4W', course_name: '200-hour 4 Weeks Intensive Yoga Teacher Training', category: 'Education', track: '4 Weeks Intensive', cohort_id: '2026-04', cohort_label: 'April 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=46&prodId=100121', price_full: 23750, currency: 'DKK', deposit_amount: '', allow_deposit: true, allow_instalments: true, max_instalments: 12, notes: '', sort_key: '', open_status: '' },
  { course_id: 'YTT200-4W', course_name: '200-hour 4 Weeks Intensive Yoga Teacher Training', category: 'Education', track: '4 Weeks Intensive', cohort_id: '2026-07', cohort_label: 'July 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=46&prodId=100211', price_full: 23750, currency: 'DKK', deposit_amount: '', allow_deposit: true, allow_instalments: true, max_instalments: 12, notes: '', sort_key: '', open_status: '' },
  { course_id: 'YTT200-4W', course_name: '200-hour 4 Weeks Intensive Yoga Teacher Training', category: 'Education', track: '4 Weeks Intensive', cohort_id: '2026-09', cohort_label: 'September 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 23750, currency: 'DKK', deposit_amount: '', allow_deposit: true, allow_instalments: true, max_instalments: 12, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },
  { course_id: 'YTT200-4W', course_name: '200-hour 4 Weeks Intensive Yoga Teacher Training', category: 'Education', track: '4 Weeks Intensive', cohort_id: '2026-10', cohort_label: 'October 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 23750, currency: 'DKK', deposit_amount: '', allow_deposit: true, allow_instalments: true, max_instalments: 12, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },
  { course_id: 'YTT200-4W', course_name: '200-hour 4 Weeks Intensive Yoga Teacher Training', category: 'Education', track: '4 Weeks Intensive', cohort_id: '2026-11', cohort_label: 'November 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 23750, currency: 'DKK', deposit_amount: '', allow_deposit: true, allow_instalments: true, max_instalments: 12, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },

  // === YTT 200h — 8 Weeks Semi-Intensive ===
  { course_id: 'YTT200-8W', course_name: '200-hour 8 Weeks Semi-Intensive Yoga Teacher Training', category: 'Education', track: '8 Weeks Semi-Intensive', cohort_id: '2026-05-06', cohort_label: 'May\u2013June 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=46&prodId=100209', price_full: 23750, currency: 'DKK', deposit_amount: '3750', allow_deposit: true, allow_instalments: true, max_instalments: 12, notes: '', sort_key: '', open_status: 'Open' },
  { course_id: 'YTT200-8W', course_name: '200-hour 8 Weeks Semi-Intensive Yoga Teacher Training', category: 'Education', track: '8 Weeks Semi-Intensive', cohort_id: '2026-10-11', cohort_label: 'October\u2013November 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 23750, currency: 'DKK', deposit_amount: '3750', allow_deposit: true, allow_instalments: true, max_instalments: 12, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },

  // === YTT 300h — Advanced ===
  { course_id: 'YTT300-ADV', course_name: '300-hour Advanced Yoga Teacher Training', category: 'Education', track: 'Advanced 300-hour', cohort_id: '2026-05-11', cohort_label: 'May\u2013November 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 0, currency: 'DKK', deposit_amount: '', allow_deposit: true, allow_instalments: true, max_instalments: 12, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },

  // === Inversions Course ===
  { course_id: 'INV-4W', course_name: 'Inversions Course', category: 'Course', track: 'Course', cohort_id: '2026-02', cohort_label: 'February 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=33&prodId=100109', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: '', sort_key: '', open_status: '' },
  { course_id: 'INV-4W', course_name: 'Inversions Course', category: 'Course', track: 'Course', cohort_id: '2026-03', cohort_label: 'March 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=33&prodId=100144', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: '', sort_key: '', open_status: '' },
  { course_id: 'INV-4W', course_name: 'Inversions Course', category: 'Course', track: 'Course', cohort_id: '2026-04', cohort_label: 'April 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=33&prodId=100145', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: '', sort_key: '', open_status: '' },
  { course_id: 'INV-4W', course_name: 'Inversions Course', category: 'Course', track: 'Course', cohort_id: '2026-05', cohort_label: 'May 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=33&prodId=100146', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: '', sort_key: '', open_status: '' },
  { course_id: 'INV-4W', course_name: 'Inversions Course', category: 'Course', track: 'Course', cohort_id: '2026-06', cohort_label: 'June 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },
  { course_id: 'INV-4W', course_name: 'Inversions Course', category: 'Course', track: 'Course', cohort_id: '2026-09', cohort_label: 'September 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },
  { course_id: 'INV-4W', course_name: 'Inversions Course', category: 'Course', track: 'Course', cohort_id: '2026-10', cohort_label: 'October 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },
  { course_id: 'INV-4W', course_name: 'Inversions Course', category: 'Course', track: 'Course', cohort_id: '2026-11', cohort_label: 'November 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },

  // === Splits Course ===
  { course_id: 'SPL-4W', course_name: 'Splits Course', category: 'Course', track: 'Course', cohort_id: '2026-02', cohort_label: 'February 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=43&prodId=100148', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: '', sort_key: '', open_status: '' },
  { course_id: 'SPL-4W', course_name: 'Splits Course', category: 'Course', track: 'Course', cohort_id: '2026-03', cohort_label: 'March 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=43&prodId=100149', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: '', sort_key: '', open_status: '' },
  { course_id: 'SPL-4W', course_name: 'Splits Course', category: 'Course', track: 'Course', cohort_id: '2026-04', cohort_label: 'April 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=43&prodId=100150', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: '', sort_key: '', open_status: '' },
  // Row 29 (corrupted SPL-4W row) intentionally omitted
  { course_id: 'SPL-4W', course_name: 'Splits Course', category: 'Course', track: 'Course', cohort_id: '2026-06', cohort_label: 'June 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },
  { course_id: 'SPL-4W', course_name: 'Splits Course', category: 'Course', track: 'Course', cohort_id: '2026-09', cohort_label: 'September 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },
  { course_id: 'SPL-4W', course_name: 'Splits Course', category: 'Course', track: 'Course', cohort_id: '2026-10', cohort_label: 'October 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },
  { course_id: 'SPL-4W', course_name: 'Splits Course', category: 'Course', track: 'Course', cohort_id: '2026-11', cohort_label: 'November 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },

  // === Backbends Course ===
  { course_id: 'BB-4W', course_name: 'Backbends Course', category: 'Course', track: 'Course', cohort_id: '2026-02', cohort_label: 'February 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=44&prodId=100138', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: '', sort_key: '', open_status: '' },
  { course_id: 'BB-4W', course_name: 'Backbends Course', category: 'Course', track: 'Course', cohort_id: '2026-03', cohort_label: 'March 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=44&prodId=100139', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: '', sort_key: '', open_status: '' },
  { course_id: 'BB-4W', course_name: 'Backbends Course', category: 'Course', track: 'Course', cohort_id: '2026-04', cohort_label: 'April 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=44&prodId=100140', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: '', sort_key: '', open_status: '' },
  { course_id: 'BB-4W', course_name: 'Backbends Course', category: 'Course', track: 'Course', cohort_id: '2026-05', cohort_label: 'May 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=5748831&stype=41&sTG=44&prodId=100141', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: '', sort_key: '', open_status: '' },
  { course_id: 'BB-4W', course_name: 'Backbends Course', category: 'Course', track: 'Course', cohort_id: '2026-06', cohort_label: 'June 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },
  { course_id: 'BB-4W', course_name: 'Backbends Course', category: 'Course', track: 'Course', cohort_id: '2026-09', cohort_label: 'September 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },
  { course_id: 'BB-4W', course_name: 'Backbends Course', category: 'Course', track: 'Course', cohort_id: '2026-10', cohort_label: 'October 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },
  { course_id: 'BB-4W', course_name: 'Backbends Course', category: 'Course', track: 'Course', cohort_id: '2026-11', cohort_label: 'November 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: '', payment_url_deposit: '', price_full: 2300, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: 'Application still not open \u2014 kontakt info@yogabible.dk', sort_key: '', open_status: '' },

  // === Mentorship ===
  { course_id: 'MENTOR', course_name: 'Mentorship & Private Training', category: 'Mentorship', track: 'Private / 1\u201312', cohort_id: 'N/A', cohort_label: 'G\u00e5 til siden', start_date: '', end_date: '', capacity: 12, waitlist_enabled: false, active: true, external_only: true, external_url: 'https://www.yogabible.dk/mentorship-private-training', payment_url_full: '', payment_url_deposit: '', price_full: 0, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: false, max_instalments: 0, notes: 'External signup only', sort_key: '', open_status: '' },

  // === Bundles — February 2026 ===
  { course_id: 'BUNDLE-INV-BB-FEB26', course_name: 'Inversions + Backbends Bundle', category: 'Bundle', track: '2-Course', cohort_id: 'BUNDLE-INV-BB-FEB26', cohort_label: 'februar 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=113', payment_url_deposit: '', price_full: 4140, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: '', sort_key: '100', open_status: 'Open' },
  { course_id: 'BUNDLE-INV-SPL-FEB26', course_name: 'Inversions + Splits Bundle', category: 'Bundle', track: '2-Course', cohort_id: 'BUNDLE-INV-SPL-FEB26', cohort_label: 'februar 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=114', payment_url_deposit: '', price_full: 4140, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: '', sort_key: '101', open_status: 'Open' },
  { course_id: 'BUNDLE-BB-SPL-FEB26', course_name: 'Backbends + Splits Bundle', category: 'Bundle', track: '2-Course', cohort_id: 'BUNDLE-BB-SPL-FEB26', cohort_label: 'februar 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=115', payment_url_deposit: '', price_full: 4140, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: '', sort_key: '102', open_status: 'Open' },
  { course_id: 'BUNDLE-ALL-FEB26', course_name: 'All-In Bundle (3 Courses)', category: 'Bundle', track: 'All-In', cohort_id: 'BUNDLE-ALL-FEB26', cohort_label: 'februar 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=125', payment_url_deposit: '', price_full: 5865, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: 'Includes 1-month pass (value 1399 kr)', sort_key: '103', open_status: 'Open' },

  // === Bundles — March 2026 ===
  { course_id: 'BUNDLE-INV-BB-MAR26', course_name: 'Inversions + Backbends Bundle', category: 'Bundle', track: '2-Course', cohort_id: 'BUNDLE-INV-BB-MAR26', cohort_label: 'marts 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=116', payment_url_deposit: '', price_full: 4140, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: '', sort_key: '110', open_status: 'Open' },
  { course_id: 'BUNDLE-INV-SPL-MAR26', course_name: 'Inversions + Splits Bundle', category: 'Bundle', track: '2-Course', cohort_id: 'BUNDLE-INV-SPL-MAR26', cohort_label: 'marts 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=117', payment_url_deposit: '', price_full: 4140, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: '', sort_key: '111', open_status: 'Open' },
  { course_id: 'BUNDLE-BB-SPL-MAR26', course_name: 'Backbends + Splits Bundle', category: 'Bundle', track: '2-Course', cohort_id: 'BUNDLE-BB-SPL-MAR26', cohort_label: 'marts 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=118', payment_url_deposit: '', price_full: 4140, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: '', sort_key: '112', open_status: 'Open' },
  { course_id: 'BUNDLE-ALL-MAR26', course_name: 'All-In Bundle (3 Courses)', category: 'Bundle', track: 'All-In', cohort_id: 'BUNDLE-ALL-MAR26', cohort_label: 'marts 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=126', payment_url_deposit: '', price_full: 5865, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: 'Includes 1-month pass (value 1399 kr)', sort_key: '113', open_status: 'Open' },

  // === Bundles — April 2026 ===
  { course_id: 'BUNDLE-INV-BB-APR26', course_name: 'Inversions + Backbends Bundle', category: 'Bundle', track: '2-Course', cohort_id: 'BUNDLE-INV-BB-APR26', cohort_label: 'april 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=119', payment_url_deposit: '', price_full: 4140, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: '', sort_key: '120', open_status: 'Open' },
  { course_id: 'BUNDLE-INV-SPL-APR26', course_name: 'Inversions + Splits Bundle', category: 'Bundle', track: '2-Course', cohort_id: 'BUNDLE-INV-SPL-APR26', cohort_label: 'april 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=120', payment_url_deposit: '', price_full: 4140, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: '', sort_key: '121', open_status: 'Open' },
  { course_id: 'BUNDLE-BB-SPL-APR26', course_name: 'Backbends + Splits Bundle', category: 'Bundle', track: '2-Course', cohort_id: 'BUNDLE-BB-SPL-APR26', cohort_label: 'april 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=121', payment_url_deposit: '', price_full: 4140, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: '', sort_key: '122', open_status: 'Open' },
  { course_id: 'BUNDLE-ALL-APR26', course_name: 'All-In Bundle (3 Courses)', category: 'Bundle', track: 'All-In', cohort_id: 'BUNDLE-ALL-APR26', cohort_label: 'april 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=127', payment_url_deposit: '', price_full: 5865, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: 'Includes 1-month pass (value 1399 kr)', sort_key: '123', open_status: 'Open' },

  // === Bundles — May 2026 ===
  { course_id: 'BUNDLE-INV-BB-MAY26', course_name: 'Inversions + Backbends Bundle', category: 'Bundle', track: '2-Course', cohort_id: 'BUNDLE-INV-BB-MAY26', cohort_label: 'maj 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=122', payment_url_deposit: '', price_full: 4140, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: '', sort_key: '130', open_status: 'Open' },
  { course_id: 'BUNDLE-INV-SPL-MAY26', course_name: 'Inversions + Splits Bundle', category: 'Bundle', track: '2-Course', cohort_id: 'BUNDLE-INV-SPL-MAY26', cohort_label: 'maj 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=123', payment_url_deposit: '', price_full: 4140, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: '', sort_key: '131', open_status: 'Open' },
  { course_id: 'BUNDLE-BB-SPL-MAY26', course_name: 'Backbends + Splits Bundle', category: 'Bundle', track: '2-Course', cohort_id: 'BUNDLE-BB-SPL-MAY26', cohort_label: 'maj 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=124', payment_url_deposit: '', price_full: 4140, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: '', sort_key: '132', open_status: 'Open' },
  { course_id: 'BUNDLE-ALL-MAY26', course_name: 'All-In Bundle (3 Courses)', category: 'Bundle', track: 'All-In', cohort_id: 'BUNDLE-ALL-MAY26', cohort_label: 'maj 2026', start_date: '', end_date: '', capacity: 12, waitlist_enabled: true, active: true, external_only: false, external_url: '', payment_url_full: 'https://clients.mindbodyonline.com/classic/ws?studioid=574883&stype=40&prodid=128', payment_url_deposit: '', price_full: 5865, currency: 'DKK', deposit_amount: '', allow_deposit: false, allow_instalments: true, max_instalments: 0, notes: 'Includes 1-month pass (value 1399 kr)', sort_key: '133', open_status: 'Open' }
];

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') return optionsResponse();
  if (event.httpMethod !== 'POST') {
    return jsonResponse(405, { ok: false, error: 'POST only' });
  }

  const user = await requireAuth(event, ['admin']);
  if (user.error) return user.error;

  const params = event.queryStringParameters || {};
  if (params.confirm !== 'seed') {
    return jsonResponse(400, { ok: false, error: 'Pass ?confirm=seed to proceed' });
  }

  const db = getDb();

  // Idempotency: skip if collection already has documents
  const existing = await db.collection('course_catalog').limit(1).get();
  if (!existing.empty) {
    return jsonResponse(200, {
      ok: false,
      error: 'Collection already has data. Delete existing items first or use the catalog-admin API.'
    });
  }

  // Batch write in chunks of 450
  const batchSize = 450;
  let written = 0;

  for (let i = 0; i < SEED_DATA.length; i += batchSize) {
    const batch = db.batch();
    const chunk = SEED_DATA.slice(i, i + batchSize);

    for (const item of chunk) {
      const ref = db.collection('course_catalog').doc();
      batch.set(ref, {
        ...item,
        created_at: new Date(),
        updated_at: new Date(),
        seeded: true
      });
    }

    await batch.commit();
    written += chunk.length;
  }

  console.log(`[catalog-seed] Seeded ${written} catalog items by ${user.email}`);

  return jsonResponse(201, {
    ok: true,
    written,
    message: `Seeded ${written} catalog items.`
  });
};
