/**
 * Social Evergreen Recycler — Yoga Bible
 * Scheduled function that automatically re-queues top-performing evergreen posts.
 *
 * Runs daily at 6am UTC. Finds published posts marked as 'recycled' status
 * whose recycleConfig.nextRecycleAt has passed, creates a new scheduled copy,
 * and updates the next recycle date.
 *
 * Also auto-identifies top performers for recycling if they haven't been
 * recycled yet (posts with high engagement and no time-sensitive content).
 *
 * Configured in netlify.toml:
 *   [functions."social-recycle"]
 *     schedule = "0 6 * * *"
 */

const { getDb, serverTimestamp } = require('./shared/firestore');
const { jsonResponse } = require('./shared/utils');

const POSTS_COLLECTION = 'social_posts';

// Engagement threshold to auto-suggest recycling (top quartile)
const AUTO_RECYCLE_MIN_ENGAGEMENT = 50;
const AUTO_RECYCLE_MIN_DAYS_OLD = 30;
const MAX_RECYCLE_COUNT = 3; // Don't recycle the same post more than 3 times

exports.handler = async () => {
  const db = getDb();

  try {
    const now = new Date();
    let recycled = 0;
    let suggested = 0;

    // ── 1. Process posts with active recycle configs ──────────────
    const recycledSnap = await db.collection(POSTS_COLLECTION)
      .where('status', '==', 'recycled')
      .limit(50)
      .get();

    for (const doc of recycledSnap.docs) {
      const post = doc.data();
      const config = post.recycleConfig;
      if (!config || !config.intervalDays) continue;

      // Calculate next recycle date
      const lastRecycled = config.lastRecycledAt
        ? (config.lastRecycledAt.toDate ? config.lastRecycledAt.toDate() : new Date(config.lastRecycledAt))
        : (post.publishedAt?.toDate ? post.publishedAt.toDate() : new Date(post.publishedAt || post.createdAt));

      const nextRecycle = new Date(lastRecycled.getTime() + config.intervalDays * 24 * 60 * 60 * 1000);

      if (nextRecycle > now) continue; // Not due yet

      // Check max recycle count
      const recycleCount = config.recycleCount || 0;
      if (recycleCount >= MAX_RECYCLE_COUNT) {
        // Max reached — stop recycling
        await db.collection(POSTS_COLLECTION).doc(doc.id).update({
          'recycleConfig.active': false,
          'recycleConfig.stoppedReason': 'max_recycle_count',
          updatedAt: serverTimestamp()
        });
        continue;
      }

      // Determine optimal posting time (vary between 9-18h CET)
      const hour = 9 + Math.floor(Math.random() * 9);
      const scheduledAt = new Date(now);
      scheduledAt.setHours(hour, Math.floor(Math.random() * 60), 0, 0);
      // If already past that hour today, schedule for tomorrow
      if (scheduledAt <= now) {
        scheduledAt.setDate(scheduledAt.getDate() + 1);
      }

      // Create recycled post copy
      const newPost = {
        caption: post.caption || '',
        platforms: post.platforms || ['instagram', 'facebook'],
        mediaUrls: post.mediaUrls || [],
        hashtags: post.hashtags || [],
        status: 'scheduled',
        scheduledAt: scheduledAt,
        publishedAt: null,
        publishResults: {},
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
        autoGenerated: true,
        recycledFrom: doc.id,
        recycleIteration: recycleCount + 1,
        mediaType: post.mediaType || 'auto',
        firstComment: post.firstComment || '',
        contentPillar: post.contentPillar || null
      };

      await db.collection(POSTS_COLLECTION).add(newPost);

      // Update original with next recycle info
      await db.collection(POSTS_COLLECTION).doc(doc.id).update({
        'recycleConfig.lastRecycledAt': serverTimestamp(),
        'recycleConfig.recycleCount': recycleCount + 1,
        'recycleConfig.nextRecycleAt': new Date(scheduledAt.getTime() + config.intervalDays * 24 * 60 * 60 * 1000),
        updatedAt: serverTimestamp()
      });

      recycled++;
      console.log(`[social-recycle] Recycled post ${doc.id} → scheduled for ${scheduledAt.toISOString()}`);
    }

    // ── 2. Auto-suggest top performers for recycling ─────────────
    const cutoffDate = new Date(now.getTime() - AUTO_RECYCLE_MIN_DAYS_OLD * 24 * 60 * 60 * 1000);

    let publishedSnap;
    try {
      publishedSnap = await db.collection(POSTS_COLLECTION)
        .where('status', '==', 'published')
        .where('publishedAt', '<=', cutoffDate)
        .limit(100)
        .get();
    } catch (indexErr) {
      console.warn('[social-recycle] Compound query needs index, using fallback:', indexErr.message);
      publishedSnap = await db.collection(POSTS_COLLECTION)
        .where('status', '==', 'published')
        .limit(100)
        .get();
    }

    for (const doc of publishedSnap.docs) {
      const post = doc.data();

      // Skip if already has recycle config or is itself recycled
      if (post.recycleConfig || post.recycledFrom) continue;

      // Calculate engagement score
      const results = post.publishResults || {};
      let totalEng = 0;
      for (const [, r] of Object.entries(results)) {
        if (r.metrics) {
          totalEng += (r.metrics.likes || 0) + (r.metrics.comments || 0) * 2 + (r.metrics.shares || 0) * 3;
        }
      }

      if (totalEng < AUTO_RECYCLE_MIN_ENGAGEMENT) continue;

      // Mark as recyclable (doesn't auto-recycle, just flags it)
      await db.collection(POSTS_COLLECTION).doc(doc.id).update({
        evergreenCandidate: true,
        evergreenScore: totalEng,
        updatedAt: serverTimestamp()
      });
      suggested++;
    }

    console.log(`[social-recycle] Done: ${recycled} recycled, ${suggested} evergreen candidates flagged`);
    return jsonResponse(200, { ok: true, recycled, suggested });
  } catch (err) {
    console.error('[social-recycle] Error:', err);
    return jsonResponse(500, { ok: false, error: err.message });
  }
};
