/**
 * Social Sync — Yoga Bible
 * Cross-module integration helpers.
 * Called by other modules (sequences, lead capture, store) to create
 * social posts triggered by business events.
 */

const { getDb, serverTimestamp } = require('./firestore');

const POSTS_COLLECTION = 'social_posts';

/**
 * Create a draft social post from a business event.
 * @param {object} opts
 * @param {string} opts.source - Event source (e.g., 'sequence', 'lead', 'store', 'application')
 * @param {string} opts.caption - Post caption
 * @param {string[]} opts.platforms - Target platforms
 * @param {string[]} opts.hashtags - Hashtags
 * @param {string} opts.mediaUrl - Optional media URL
 * @param {string} opts.scheduledAt - Optional ISO date to schedule
 * @param {object} opts.metadata - Additional metadata
 */
async function createSocialPost(opts) {
  const db = getDb();

  const postData = {
    caption: opts.caption || '',
    platforms: opts.platforms || ['instagram', 'facebook'],
    mediaUrls: opts.mediaUrl ? [opts.mediaUrl] : [],
    hashtags: opts.hashtags || [],
    status: opts.scheduledAt ? 'scheduled' : 'draft',
    scheduledAt: opts.scheduledAt ? new Date(opts.scheduledAt) : null,
    publishedAt: null,
    publishResults: {},
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
    autoGenerated: true,
    sourceEvent: opts.source || 'unknown',
    sourceMetadata: opts.metadata || {},
    mediaType: 'auto'
  };

  const ref = await db.collection(POSTS_COLLECTION).add(postData);
  console.log(`[social-sync] Created post ${ref.id} from ${opts.source}`);
  return ref.id;
}

/**
 * Create a social proof post when leads hit a milestone.
 * @param {string} milestone - e.g., 'new_lead_batch', 'application_received', 'prep_phase_purchased'
 * @param {object} data - Contextual data
 */
async function createMilestonePost(milestone, data) {
  const templates = {
    new_lead_batch: {
      caption: `Another week of incredible interest in yoga teacher training! ✨\n\nThe community keeps growing, and we're so grateful for every single one of you who's exploring this path.\n\nWhether you're still thinking or ready to start — we're here for you.\n\n📍 Torvegade 66, Copenhagen`,
      hashtags: ['#yogabible', '#yogateachertraining', '#copenhagen', '#ytt200', '#yogacommunity']
    },
    application_received: {
      caption: `Another future yoga teacher just took the first step! 🙏\n\nThe feeling of receiving an application never gets old. Someone out there just decided to change their life — and that's worth celebrating.\n\n📖 Start your journey: yogabible.dk`,
      hashtags: ['#yogabible', '#futureyogateacher', '#yogateachertraining', '#copenhagen', '#ryt200']
    },
    prep_phase_purchased: {
      caption: `The Preparation Phase is filling up! 🧘\n\nEvery new student who starts their Preparation Phase brings fresh energy to the studio. Welcome to the Yoga Bible family.\n\n📍 See you at Torvegade 66`,
      hashtags: ['#yogabible', '#yogateachertraining', '#preparationphase', '#copenhagen', '#yogalife']
    }
  };

  const template = templates[milestone];
  if (!template) {
    console.log(`[social-sync] No template for milestone: ${milestone}`);
    return null;
  }

  return createSocialPost({
    source: 'milestone:' + milestone,
    caption: template.caption,
    hashtags: template.hashtags,
    platforms: ['instagram', 'facebook'],
    metadata: data
  });
}

/**
 * Create a social post matching a nurture sequence email theme.
 * Called by process-sequences.js when an email is sent.
 * @param {string} sequenceId - Firestore sequence ID
 * @param {number} stepIndex - Step number
 * @param {string} theme - Step theme/subject
 */
async function createSequenceSyncPost(sequenceId, stepIndex, theme) {
  // Avoid duplicate posts for the same sequence step within 24 hours
  const db = getDb();
  const dayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000);

  const existing = await db.collection(POSTS_COLLECTION)
    .where('sourceEvent', '==', 'sequence:' + sequenceId)
    .where('createdAt', '>=', dayAgo)
    .limit(1)
    .get();

  if (!existing.empty) {
    console.log(`[social-sync] Skipping sequence sync — already posted for ${sequenceId} today`);
    return null;
  }

  // Schedule the post 2 hours after the email for multi-channel reinforcement
  const scheduleTime = new Date(Date.now() + 2 * 60 * 60 * 1000);

  return createSocialPost({
    source: 'sequence:' + sequenceId,
    caption: `💡 ${theme}\n\nWe just shared some thoughts about this with our community — and wanted you to hear it too.\n\nWhat's your experience? Drop a comment below 👇`,
    hashtags: ['#yogabible', '#yogateachertraining', '#yogalife', '#copenhagen'],
    platforms: ['instagram', 'facebook'],
    scheduledAt: scheduleTime.toISOString(),
    metadata: { sequenceId, stepIndex }
  });
}

module.exports = {
  createSocialPost,
  createMilestonePost,
  createSequenceSyncPost
};
